import 'core-js'
export * from './ResourceCollection'
export * from './PageCollection'
export * from './IResource'
export * from './ClassType'
export * from './Dictionary'
export * from './QueryFilter'
